//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCore.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archivos
    {
        public int id_archivo { get; set; }
        public Nullable<int> id_expediente { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string nombre { get; set; }
        public string tipo_mime { get; set; }
        public long tamano_bytes { get; set; }
        public byte[] contenido { get; set; }
        public string estado { get; set; }
        public System.DateTime fecha_carga { get; set; }
    
        public virtual Expedientes Expedientes { get; set; }
        public virtual tbUsuario tbUsuario { get; set; }
    }
}
