//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCore.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public long id_bitacora { get; set; }
        public System.DateTime fecha { get; set; }
        public string nivel { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string controlador { get; set; }
        public string accion { get; set; }
        public string mensaje { get; set; }
        public string stack_trace { get; set; }
        public string ip_origen { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
    }
}
