//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCore.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public long id_bitacora { get; set; }
        public System.DateTime fecha { get; set; }
        public string nivel { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string controlador { get; set; }
        public string accion { get; set; }
        public string mensaje { get; set; }
        public string stack_trace { get; set; }
        public string ip_origen { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
    }
}
