//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCore.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Citas()
        {
            this.Citas1 = new HashSet<Citas>();
            this.HistorialMedico = new HashSet<HistorialMedico>();
        }
    
        public int id_cita { get; set; }
        public int id_paciente { get; set; }
        public int id_doctor { get; set; }
        public System.DateTime fecha_cita { get; set; }
        public int duracion_min { get; set; }
        public string motivo { get; set; }
        public string estado { get; set; }
        public string motivo_cancelacion { get; set; }
        public Nullable<int> id_cita_anterior { get; set; }
        public System.DateTime fecha_creacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Citas> Citas1 { get; set; }
        public virtual Citas Citas2 { get; set; }
        public virtual Doctores Doctores { get; set; }
        public virtual Pacientes Pacientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialMedico> HistorialMedico { get; set; }
    }
}
