//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCore.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Citas()
        {
            this.Citas1 = new HashSet<Citas>();
            this.HistorialMedico = new HashSet<HistorialMedico>();
        }
    
        public int id_cita { get; set; }
        public int id_paciente { get; set; }
        public int id_doctor { get; set; }
        public System.DateTime fecha_cita { get; set; }
        public int duracion_min { get; set; }
        public string motivo { get; set; }
        public string estado { get; set; }
        public Nullable<int> id_cita_anterior { get; set; }
        public System.DateTime fecha_creacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Citas> Citas1 { get; set; }
        public virtual Citas Citas2 { get; set; }
        public virtual Doctores Doctores { get; set; }
        public virtual Pacientes Pacientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialMedico> HistorialMedico { get; set; }
    }
}
