//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCore.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialMedico
    {
        public int id_historial { get; set; }
        public int id_expediente { get; set; }
        public Nullable<int> id_cita { get; set; }
        public int id_doctor { get; set; }
        public System.DateTime fecha_consulta { get; set; }
        public string sintomas { get; set; }
        public string diagnostico { get; set; }
        public string tratamiento { get; set; }
        public string observaciones { get; set; }
        public string medicamentos { get; set; }
        public Nullable<System.DateTime> proxima_cita { get; set; }
    
        public virtual Citas Citas { get; set; }
        public virtual Doctores Doctores { get; set; }
        public virtual Expedientes Expedientes { get; set; }
    }
}
