//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCore.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorariosMedicos
    {
        public int id_horario { get; set; }
        public int id_doctor { get; set; }
        public byte dia_semana { get; set; }
        public System.TimeSpan hora_inicio { get; set; }
        public System.TimeSpan hora_fin { get; set; }
        public int duracion_cita_min { get; set; }
        public string estado { get; set; }
    
        public virtual Doctores Doctores { get; set; }
    }
}
