//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCore.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificaciones
    {
        public int id_notificacion { get; set; }
        public Nullable<int> id_usuario_destino { get; set; }
        public string correo_destino { get; set; }
        public string tipo { get; set; }
        public string asunto { get; set; }
        public string cuerpo { get; set; }
        public string estado { get; set; }
        public System.DateTime fecha_envio { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
    }
}
