//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCore.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificaciones
    {
        public int id_notificacion { get; set; }
        public Nullable<int> id_usuario_destino { get; set; }
        public string correo_destino { get; set; }
        public string tipo { get; set; }
        public string asunto { get; set; }
        public string cuerpo { get; set; }
        public string estado { get; set; }
        public System.DateTime fecha_envio { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
    }
}
